image: ubuntu:trusty

variables:
  GIT_STRATEGY: "clone"
  GIT_CHECKOUT: "true"

push_to_github: 
  stage: deploy
  tags:
    - docker
  script:
    - docker build .
    #- git pull
    #- git push -f https://jbharter:$GH_TOKEN@github.com/jbharter/xyce-deps-docker.git master