image: docker:latest

services:
 - docker:dind

variables:
  GIT_STRATEGY: "clone"
  GIT_CHECKOUT: "true"
  CI_REGISTRY_USER: "jbharter"
  CI_REGISTRY: "index.docker.io"
  CI_REGISTRY_IMAGE: "index.docker.io/jbharter/xyce-deps-docker"
  DOCKER_HOST: tcp://localhost:2375
  
stages:
  - build
  - test
  - deploy
  
before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-master:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master



# build_dockerimage:
#   stage: build
#   script:
#     - docker build .
    
# push_to_github: 
#   stage: deploy
#   script:
#     - date
    #- docker build .
    #- git pull
    #- git push -f https://jbharter:$GH_TOKEN@github.com/jbharter/xyce-deps-docker.git master