image: docker:latest
services:
 - docker:dind

variables:
  GIT_STRATEGY: "clone"
  GIT_CHECKOUT: "true"
  DOCKER_HOST: tcp://localhost:2375
  
stages:
  - build
  - test
  - deploy

build_dockerimage:
  stage: build
  script:
    - docker build .
    
push_to_github: 
  stage: deploy
  script:
    - date
    #- docker build .
    #- git pull
    #- git push -f https://jbharter:$GH_TOKEN@github.com/jbharter/xyce-deps-docker.git master