push_to_github: 
  stage: deploy
  tags:
    - shell
  script:
    - git remote remove github
    - git remote add github https://jbharter:$GH_TOKEN@github.com/jbharter/xyce-deps-docker.git
    - git push github master