push_to_github: 
  stage: deploy
  tags:
    - shell
    - osx
  script:
    - git pull https://jbharter:$GH_TOKEN@github.com/jbharter/xyce-deps-docker.git
    - git push https://jbharter:$GH_TOKEN@github.com/jbharter/xyce-deps-docker.git master