sudo: required

services:
  - docker

script:
  - docker build -t jbharter/xyce-deps-docker .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push jbharter/xyce-deps-docker:release;
    fi
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push jbharter/xyce-deps-docker:latest;
    fi
